accepted = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "Unicode-3.0",
    "CDLA-Permissive-2.0",
    "Zlib",
]

# AWS-LC's composite license files contain component-specific attributions that
# are lost if their individual SPDX terms are synthesized independently.
[aws-lc-rs.clarify]
license = "ISC AND (Apache-2.0 OR ISC)"

[[aws-lc-rs.clarify.files]]
path = "LICENSE"
checksum = "b50b376e7d24a0598488b730c3034ffcd0b58dd36c0913a24b9903a3cfd04bf7"

[aws-lc-sys.clarify]
license = "ISC AND (Apache-2.0 OR ISC) AND Apache-2.0 AND MIT AND BSD-3-Clause AND (Apache-2.0 OR ISC OR MIT) AND (Apache-2.0 OR ISC OR MIT-0)"

[[aws-lc-sys.clarify.files]]
path = "LICENSE"
license = "ISC"
checksum = "728536b4160e051f86d7c9c388f704866b3d512cd7df97ac3516c65279523c4e"

# Preserve the upstream files whole because they contain copyright notices and
# secondary component terms in addition to the crate-level SPDX expression.
[chrono.clarify]
license = "MIT OR Apache-2.0"

[[chrono.clarify.files]]
path = "LICENSE.txt"
license = "MIT"
checksum = "946c9835d8034d24404f8cfec5f4654cee5dad17e944afc3d06d742cf2882831"

[sha1_smol.clarify]
license = "BSD-3-Clause"

[[sha1_smol.clarify.files]]
path = "LICENSE"
license = "BSD-3-Clause"
checksum = "282a21b0710441c364025461a447362daf18f5798a7b72ae2f801a2aa536da51"
