#!/usr/bin/env python3
"""Validate the assembled research corpus without network access.

This checks structure, citation closure, bibliography coverage, and validation
artifact reachability. It does not establish that a source or research claim is
true; that remains the job of source audit and whole-corpus review.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict, deque
from pathlib import Path

sys.dont_write_bytecode = True

from compile_sources import (  # noqa: E402
    DEFINITION_RE,
    LOCAL_REFERENCES,
    OUTPUT,
    ROOT,
    URL_RE,
    canonical_url,
    parse_local_definitions,
    render,
)


INDEX = ROOT / "index.md"
LINK_RE = re.compile(r"!?\[[^\]\n]*\]\(([^)\n]+)\)")
CITATION_RE = re.compile(r"\[([^\]\n]+)\]\[([^\]\n]+)\]")
LOWER_KEY_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
TITLE_RE = re.compile(r"(?:“([^”]+)”|\*([^*]+)\*)")


def display(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def normalize_title(definition: str) -> set[str]:
    match = TITLE_RE.search(definition)
    if not match:
        return set()
    title = next(group for group in match.groups() if group is not None)
    return {
        word
        for word in re.findall(r"[a-z0-9]+", title.casefold())
        if len(word) > 2
    }


def local_target(source: Path, raw: str) -> Path | None:
    target = raw.strip()
    if target.startswith("<") and target.endswith(">"):
        target = target[1:-1]
    target = target.split(maxsplit=1)[0]
    if target.startswith(("https://", "http://", "mailto:", "#")):
        return None
    target = target.split("#", 1)[0].split("?", 1)[0]
    if not target:
        return None
    return (source.parent / target).resolve()


def main() -> int:
    errors: list[str] = []
    markdown = sorted(
        path for path in ROOT.rglob("*.md") if ".git" not in path.parts
    )
    forbidden_generated = sorted(
        path
        for path in ROOT.rglob("*")
        if ".git" not in path.parts
        and (path.name == "__pycache__" or path.suffix in {".pyc", ".pyo"})
    )
    for path in forbidden_generated:
        errors.append(f"{display(path)}: generated bytecode/cache is forbidden")
    known_markdown = {path.resolve() for path in markdown}
    edges: dict[Path, set[Path]] = defaultdict(set)
    definitions_by_url: dict[str, list[tuple[Path, str, str]]] = defaultdict(list)
    root_linked_artifacts: set[Path] = set()
    citation_uses = 0

    for path in markdown:
        text = path.read_text(encoding="utf-8")
        reference_at = text.find(LOCAL_REFERENCES)
        body = text if reference_at < 0 else text[:reference_at]
        parsed_definitions = parse_local_definitions(text)
        definitions: dict[str, str] = {}
        for key, definition in parsed_definitions:
            if key in definitions:
                errors.append(f"{display(path)}: duplicate local reference [{key}]")
            else:
                definitions[key] = definition

        if path != OUTPUT:
            definitions_before = DEFINITION_RE.findall(body)
            for key, _ in definitions_before:
                errors.append(
                    f"{display(path)}: reference definition [{key}] precedes Local References"
                )

        citations: set[str] = set()
        for left, right in CITATION_RE.findall(body):
            citation_uses += 1
            if left != right:
                errors.append(f"{display(path)}: mismatched citation [{left}][{right}]")
                continue
            if not LOWER_KEY_RE.fullmatch(left):
                errors.append(f"{display(path)}: invalid citation key [{left}]")
                continue
            citations.add(left)
            if left not in definitions:
                errors.append(
                    f"{display(path)}: citation [{left}][{left}] has no local definition"
                )

        if citations and reference_at < 0:
            errors.append(f"{display(path)}: citations but no Local References section")

        if path != OUTPUT:
            for key in sorted(definitions.keys() - citations):
                errors.append(f"{display(path)}: unused local reference [{key}]")

        for key, definition in definitions.items():
            if not LOWER_KEY_RE.fullmatch(key):
                errors.append(f"{display(path)}: invalid reference key [{key}]")
            urls = URL_RE.findall(definition)
            if not urls:
                errors.append(f"{display(path)}: reference [{key}] has no https URL")
                continue
            canonical = canonical_url(urls[0])
            definitions_by_url[canonical].append((path, key, definition))

        for raw in LINK_RE.findall(text):
            target = local_target(path, raw)
            if target is None:
                continue
            try:
                target.relative_to(ROOT)
            except ValueError:
                errors.append(f"{display(path)}: local link escapes corpus: {raw}")
                continue
            if not target.exists():
                errors.append(f"{display(path)}: broken local link: {raw}")
                continue
            if target in known_markdown:
                edges[path.resolve()].add(target)
            if path == INDEX:
                root_linked_artifacts.add(target)

    # Catch materially different titles attached to one source while allowing
    # harmless venue/access-date formatting differences between subcorpora.
    for url, records in sorted(definitions_by_url.items()):
        titles = [
            (path, key, normalize_title(definition))
            for path, key, definition in records
            if path != OUTPUT
        ]
        nonempty = [(path, key, title) for path, key, title in titles if title]
        for index, (left_path, left_key, left_title) in enumerate(nonempty):
            for right_path, right_key, right_title in nonempty[index + 1 :]:
                if left_title.isdisjoint(right_title):
                    errors.append(
                        f"canonical URL {url} has conflicting titles in "
                        f"{display(left_path)}:[{left_key}] and "
                        f"{display(right_path)}:[{right_key}]"
                    )
                    break

    reachable: set[Path] = set()
    queue: deque[Path] = deque([INDEX.resolve()])
    while queue:
        current = queue.popleft()
        if current in reachable or current not in known_markdown:
            continue
        reachable.add(current)
        queue.extend(edges[current])
    for path in sorted(known_markdown - reachable):
        errors.append(f"{display(path)}: not reachable from index.md")

    expected_artifacts = {
        path.resolve()
        for path in ROOT.rglob("*")
        if path.is_file()
        and ".git" not in path.parts
        and (
            "data" in path.relative_to(ROOT).parts
            or path.suffix in {".csv", ".py"}
        )
        and "__pycache__" not in path.parts
    }
    for artifact in sorted(expected_artifacts - root_linked_artifacts):
        errors.append(
            f"index.md: validation artifact not listed under Supplementary code: "
            f"{display(artifact)}"
        )

    if OUTPUT.read_text(encoding="utf-8") != render():
        errors.append("sources.md: stale; run data/compile_sources.py")

    if errors:
        print(f"FAILED: {len(errors)} error(s)", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    canonical_local_urls = {
        url
        for url, records in definitions_by_url.items()
        if any(path != OUTPUT for path, _, _ in records)
    }
    print(
        "OK: "
        f"{len(markdown)} markdown files, "
        f"{citation_uses} citation uses, "
        f"{len(canonical_local_urls)} canonical sources, "
        f"{len(expected_artifacts)} validation artifacts"
    )
    print("all_markdown_reachable=true")
    print("all_citations_locally_defined=true")
    print("master_bibliography_current=true")
    print("all_validation_artifacts_listed=true")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
